name: Build and test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run test
